image: node:18

# Define reusable script sections
definitions:
  scripts:
    - &install-and-build
      - echo "Installing dependencies..."
      - npm ci
      - echo "Running build..."
      - npm run build
      - echo "Running linting..."
      - npm run lint
  caches:
    node: node_modules

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script: *install-and-build

  branches:
    main:
      - step:
          name: Build and Test
          caches:
            - node
          script: *install-and-build
      - step:
          name: Deploy to Production
          deployment: production
          script:
            - echo "=== Deploy to Launch Production ==="
            - echo "Latest Commit:" && git log -1 --pretty=format:"%H - %s"
            - echo "Installing CLI tools..."
            - npm install -g @contentstack/cli
            - npm install otplib
            - echo "Setting Launch region to AWS-NA..."
            - csdx config:set:region AWS-NA
            - echo "Logging in to Contentstack..."
            - node csdx-login.js
            - echo "Verifying login..."
            - csdx auth:whoami
            - echo "Deploying to Launch..."
            - csdx launch --redeploy-latest
            - echo "Production deployment completed!"

